### ISSUE TITLE
Fabric mod incompatibility risk

### ISSUE THREAD

**Issue by teddyxlandlee** [alexsocha/luckyblock#25]
I noticed that the Fabric version's JAR of this mod simply extracts Kotlin Runtime Environment into the jar itself. It can make other Kotlin mod incompatible with Lucky Block Mod.  
Consider using [`fabric-language-kotlin`](https://github.com/FabricMC/fabric-language-kotlin) as a dependency. You can use `include(...)` in `build.gradle` to include FLK and Kotlin RE.  
I've sent a PR in #26. Good Luck!

**Comment by alexsocha** [comment]
Thanks, you're absolutely right, there's a risk of incompatibility if I bundle kotlin-stdlib at the top level of the jar. I've solved this by relocating kotlin-stdlib to the `mod.lucky` namespace using the Shadow plugin, you can see here if interested: https://github.com/alexsocha/luckyblock/pull/28

I prefer this over `fabric-language-kotlin`, since it's a more standard solution that will also work with Forge (once I migrate that over to the new kotlin codebase), plus it comes with a nice minimization feature which brings the jar down to 1.8M

**Comment by teddyxlandlee** [comment]
Sorry to reply you too late.  
As I unzip `luckyblock-1.17.0-1-fabric.jar` I saw this very happily, which is one of the BEST solution that I have NEVER thought.
 -- though not using `fabric-language-kotlin`, it presents the best compatibility & the smallest file size (only 1891KB in total).
![Screenshot](https://i.loli.net/2021/09/11/T6wNQqCEdBivUMy.png)
